/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const balloon = (props) => {
  const { nodes, materials } = useGLTF('./models/balloon.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BALLOON.geometry} material={materials.gold} position={[0, 0.25, 0]} />
    </group>
  )
}

export default balloon

useGLTF.preload('./models/balloon.gltf')
