/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const cpgModel = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/CpgModel.glb')
  const { actions, names } = useAnimations(animations, group)
  
  useEffect (() => {
      names.forEach(name =>
          actions[name].reset().fadeIn(0.5).play()
        )
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Emblem" geometry={nodes.Emblem.geometry} material={materials['Material.002']} position={[-0.02, 0.12, 0]} rotation={[0, 0, -Math.PI]} scale={[-0.66, -0.66, -0.12]} />
        <group name="toadstool" position={[-1.93, 0.19, 0.48]} rotation={[0, 0.22, -0.14]} scale={6.45}>
          <mesh name="BezierCurve" geometry={nodes.BezierCurve.geometry} material={materials['hut.001']} />
          <mesh name="BezierCurve_1" geometry={nodes.BezierCurve_1.geometry} material={materials['Stiel.001']} />
          <mesh name="BezierCurve_2" geometry={nodes.BezierCurve_2.geometry} material={materials.Lammelleln} />
          <mesh name="BezierCurve_3" geometry={nodes.BezierCurve_3.geometry} material={materials['Stiel.002']} />
          <mesh name="BezierCurve_4" geometry={nodes.BezierCurve_4.geometry} material={materials['Stiel.003']} />
          <mesh name="BezierCurve_5" geometry={nodes.BezierCurve_5.geometry} material={materials.boden} />
        </group>
        <group name="Toadstool_No_4_(Amanita_Muscaria)" position={[0.44, -0.02, 1.99]} rotation={[0, 0.22, 0]} scale={7.5}>
          <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Stiel.004']} />
          <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={materials['Stiel.002.krempe']} />
          <mesh name="Circle_2" geometry={nodes.Circle_2.geometry} material={materials.Lamellen} />
          <mesh name="Circle_3" geometry={nodes.Circle_3.geometry} material={materials['hut.002']} />
          <mesh name="Circle_4" geometry={nodes.Circle_4.geometry} material={materials.erde} />
          <mesh name="Circle_5" geometry={nodes.Circle_5.geometry} material={materials.rinde} />
          <mesh name="Circle_6" geometry={nodes.Circle_6.geometry} material={materials.Pickel} />
        </group>
        <group name="Toadstool_No_4_(Amanita_Muscaria)001" position={[1.98, -0.02, -0.4]} rotation={[0, 0.22, 0.2]} scale={[6.45, 5.17, 6.45]}>
          <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Stiel.004']} />
          <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={materials['Stiel.002.krempe']} />
          <mesh name="Circle_2" geometry={nodes.Circle_2.geometry} material={materials.Lamellen} />
          <mesh name="Circle_3" geometry={nodes.Circle_3.geometry} material={materials['hut.002']} />
          <mesh name="Circle_4" geometry={nodes.Circle_4.geometry} material={materials.erde} />
          <mesh name="Circle_5" geometry={nodes.Circle_5.geometry} material={materials.rinde} />
          <mesh name="Circle_6" geometry={nodes.Circle_6.geometry} material={materials.Pickel} />
        </group>
        <group name="Toadstool_No_4_(Amanita_Muscaria)002" position={[-0.48, -0.02, -2.11]} rotation={[2.12, 1.32, -2.13]} scale={6.45}>
          <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Stiel.004']} />
          <mesh name="Circle001_1" geometry={nodes.Circle001_1.geometry} material={materials['Stiel.002.krempe']} />
          <mesh name="Circle001_2" geometry={nodes.Circle001_2.geometry} material={materials.Lamellen} />
          <mesh name="Circle001_3" geometry={nodes.Circle001_3.geometry} material={materials['hut.002']} />
          <mesh name="Circle001_4" geometry={nodes.Circle001_4.geometry} material={materials.erde} />
          <mesh name="Circle001_5" geometry={nodes.Circle001_5.geometry} material={materials.rinde} />
          <mesh name="Circle001_6" geometry={nodes.Circle001_6.geometry} material={materials.Pickel} />
        </group>
        <group name="toadstool001" position={[-1.02, 0.08, 1.7]} rotation={[-0.45, 1.2, 0.58]} scale={6.45}>
          <mesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials['hut.001']} />
          <mesh name="BezierCurve001_1" geometry={nodes.BezierCurve001_1.geometry} material={materials['Stiel.001']} />
          <mesh name="BezierCurve001_2" geometry={nodes.BezierCurve001_2.geometry} material={materials.Lammelleln} />
          <mesh name="BezierCurve001_3" geometry={nodes.BezierCurve001_3.geometry} material={materials['Stiel.002']} />
          <mesh name="BezierCurve001_4" geometry={nodes.BezierCurve001_4.geometry} material={materials['Stiel.003']} />
          <mesh name="BezierCurve001_5" geometry={nodes.BezierCurve001_5.geometry} material={materials.boden} />
        </group>
        <group name="Toadstool_No_4_(Amanita_Muscaria)003" position={[1.73, -0.02, 1.09]} rotation={[0.26, 1, -0.08]} scale={[4.14, 6.45, 4.14]}>
          <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Stiel.004']} />
          <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={materials['Stiel.002.krempe']} />
          <mesh name="Circle002_2" geometry={nodes.Circle002_2.geometry} material={materials.Lamellen} />
          <mesh name="Circle002_3" geometry={nodes.Circle002_3.geometry} material={materials['hut.002']} />
          <mesh name="Circle002_4" geometry={nodes.Circle002_4.geometry} material={materials.erde} />
          <mesh name="Circle002_5" geometry={nodes.Circle002_5.geometry} material={materials.rinde} />
          <mesh name="Circle002_6" geometry={nodes.Circle002_6.geometry} material={materials.Pickel} />
        </group>
        <group name="Toadstool_No_4_(Amanita_Muscaria)004" position={[1.12, -0.02, -1.68]} rotation={[-0.17, 1, 0.23]} scale={6.45}>
          <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Stiel.004']} />
          <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={materials['Stiel.002.krempe']} />
          <mesh name="Circle002_2" geometry={nodes.Circle002_2.geometry} material={materials.Lamellen} />
          <mesh name="Circle002_3" geometry={nodes.Circle002_3.geometry} material={materials['hut.002']} />
          <mesh name="Circle002_4" geometry={nodes.Circle002_4.geometry} material={materials.erde} />
          <mesh name="Circle002_5" geometry={nodes.Circle002_5.geometry} material={materials.rinde} />
          <mesh name="Circle002_6" geometry={nodes.Circle002_6.geometry} material={materials.Pickel} />
        </group>
        <group name="Toadstool_No_4_(Amanita_Muscaria)005" position={[-1.83, -0.02, -1.15]} rotation={[0, 1.01, 0]} scale={4.84}>
          <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Stiel.004']} />
          <mesh name="Circle003_1" geometry={nodes.Circle003_1.geometry} material={materials['Stiel.002.krempe']} />
          <mesh name="Circle003_2" geometry={nodes.Circle003_2.geometry} material={materials.Lamellen} />
          <mesh name="Circle003_3" geometry={nodes.Circle003_3.geometry} material={materials['hut.002']} />
          <mesh name="Circle003_4" geometry={nodes.Circle003_4.geometry} material={materials.erde} />
          <mesh name="Circle003_5" geometry={nodes.Circle003_5.geometry} material={materials.rinde} />
          <mesh name="Circle003_6" geometry={nodes.Circle003_6.geometry} material={materials.Pickel} />
        </group>
      </group>
    </group>
  )
}

export default cpgModel
useGLTF.preload('./models/CpgModel.glb')
